apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-db-volume
  namespace: svtprometheus
spec:
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  storageClassName: "nfs"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.1.41.12
    path: /k8s/pvc/prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  namespace: svtprometheus
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi